FROM python:3.9-slim

# Install networking tools
RUN apt-get update && apt-get install -y iputils-ping telnet && apt-get clean

# Set the working directory
WORKDIR /app

# Copy script and install dependencies
COPY producer.py /app/producer.py
COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

# Run the producer script
CMD ["python", "producer.py"]